const colors = {
  light: {
    background: "#ffffff",
    foreground: "#0b1f3a",
    card: "#ffffff",
    cardForeground: "#0b1f3a",
    primary: "#1e6bf0",
    primaryForeground: "#ffffff",
    primarySoft: "#e8f0ff",
    secondary: "#f3f6fb",
    secondaryForeground: "#0b1f3a",
    muted: "#f3f6fb",
    mutedForeground: "#6b7a92",
    border: "#e6ecf5",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    success: "#16a34a",
    successSoft: "#dcfce7",
    warning: "#f59e0b",
    gradientFrom: "#1e6bf0",
    gradientTo: "#0b3fb5",
  },
  dark: {
    background: "#0a1220",
    foreground: "#e6ecf5",
    card: "#121c2e",
    cardForeground: "#e6ecf5",
    primary: "#5a9bff",
    primaryForeground: "#0a1220",
    primarySoft: "#1a2a47",
    secondary: "#1a2336",
    secondaryForeground: "#e6ecf5",
    muted: "#1a2336",
    mutedForeground: "#8a99b5",
    border: "#1f2a40",
    destructive: "#f87171",
    destructiveForeground: "#0a1220",
    success: "#22c55e",
    successSoft: "#14532d",
    warning: "#fbbf24",
    gradientFrom: "#5a9bff",
    gradientTo: "#1e6bf0",
  },
};

export default colors;
